"""System prompts for Seller agents."""

from .inventory_manager import (
    INVENTORY_MANAGER_SYSTEM_PROMPT,
    DEAL_EVALUATION_PROMPT,
    YIELD_OPTIMIZATION_PROMPT,
    CROSS_SELL_PROMPT,
    PORTFOLIO_MANAGEMENT_PROMPT,
)

__all__ = [
    "INVENTORY_MANAGER_SYSTEM_PROMPT",
    "DEAL_EVALUATION_PROMPT",
    "YIELD_OPTIMIZATION_PROMPT",
    "CROSS_SELL_PROMPT",
    "PORTFOLIO_MANAGEMENT_PROMPT",
]
